version: "1"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      languages:
        javascript:
          mass_threshold: 85
  identical-code:
    config:
      languages:
        javascript:
          mass_threshold: 85
